---
- name: Converge base system
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../group_vars/all/main.yml

  roles:
    - role: common_base
    - role: xdg_base
    - role: doppler_setup
    - role: neovim_setup
